name: "certstream"
description: "Cli for calidogs certstream"
note: ""
web_url: "https://github.com/pkgforge-security/certstream-old"
repo_url: "https://github.com/pkgforge-security/certstream-old"
path: "/"
bins:
  - "certstream"