name: "fget"
description: "Multithread download for a list of files."
note: ""
web_url: "https://github.com/pkgforge-security/fget"
repo_url: "https://github.com/pkgforge-security/fget"
path: "/"
bins:
  - "fget"
