name: "subxtract"
description: "Public-Suffix based TLDs (Top-Level-Domains) & Root Domain Extractor"
note: ""
web_url: "https://github.com/pkgforge-security/subxtract"
repo_url: "https://github.com/pkgforge-security/subxtract"
path: "/"
bins:
  - "subxtract"
